IOP_BIN = bdm_query.irx
IOP_OBJS = bdm_query.o imports.o

IOP_IMPORT_INCS += \
	fs/bdm \
	system/sifcmd \
	system/sysclib \
	system/threadman

include $(PS2SDK)/Defs.make
include ../../modules/Rules.bin.make
include $(PS2SDK)/samples/Makefile.iopglobal
