#!/usr/bin/env python3
import argparse
from pathlib import Path
import sys

REPO_ROOT = Path(__file__).resolve().parents[1]
MANIFEST = REPO_ROOT / "assets/embed_manifest.txt"
OUT_C = REPO_ROOT / "asm/embedded_assets.c"


def parse_manifest(path: Path):
    entries = []
    seen = set()
    with path.open("r", encoding="utf-8") as f:
        for lineno, raw in enumerate(f, 1):
            line = raw.strip()
            if not line or line.startswith("#"):
                continue
            if "|" not in line:
                raise ValueError(f"{path}:{lineno}: invalid format (expected VIRTUAL_PATH|SOURCE_PATH)")
            virtual, source = [part.strip() for part in line.split("|", 1)]
            if not virtual or not source:
                raise ValueError(f"{path}:{lineno}: empty virtual/source path")
            if virtual.startswith("/"):
                raise ValueError(f"{path}:{lineno}: virtual path must not start with '/': {virtual}")
            if virtual in seen:
                raise ValueError(f"{path}:{lineno}: duplicate virtual path: {virtual}")
            seen.add(virtual)
            source_path = REPO_ROOT / source
            if not source_path.is_file():
                raise ValueError(f"{path}:{lineno}: missing source file: {source}")
            entries.append((virtual, source, source_path.read_bytes()))
    entries.sort(key=lambda x: x[0])
    return entries


def to_c_string(text: str):
    return text.replace("\\", "\\\\").replace('"', '\\"')


def render(entries):
    out = []
    out.append("/* Auto-generated by tools/gen_embed_assets.py. Do not edit. */")
    out.append("#include <stddef.h>")
    out.append("#include <stdint.h>")
    out.append("")
    out.append("typedef struct {")
    out.append("  const char *path;")
    out.append("  const unsigned char *data;")
    out.append("  unsigned int size;")
    out.append("} embed_asset_t;")
    out.append("")

    for idx, (_, _, data) in enumerate(entries):
        out.append(f"static const unsigned char asset_{idx}[] = {{")
        if data:
            for start in range(0, len(data), 12):
                chunk = data[start:start + 12]
                line = ", ".join(f"0x{b:02x}" for b in chunk)
                out.append(f"  {line},")
        out.append("};")
        out.append(f"static const unsigned int asset_{idx}_size = {len(data)}u;")
        out.append("")

    out.append("const embed_asset_t g_embed_assets[] = {")
    for idx, (virtual, _, _) in enumerate(entries):
        out.append(f"  {{\"{to_c_string(virtual)}\", asset_{idx}, asset_{idx}_size}},")
    out.append("};")
    out.append(f"const unsigned int g_embed_assets_count = {len(entries)}u;")
    out.append("")
    return "\n".join(out)


def main():
    parser = argparse.ArgumentParser(description="Generate embedded asset C translation unit")
    parser.add_argument("--manifest", default=str(MANIFEST), help="manifest file")
    parser.add_argument("--output", default=str(OUT_C), help="output C file")
    parser.add_argument("--check", action="store_true", help="validate manifest only")
    args = parser.parse_args()

    manifest = Path(args.manifest)
    output = Path(args.output)

    try:
        entries = parse_manifest(manifest)
    except Exception as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1

    if args.check:
        print(f"Manifest OK: {len(entries)} assets")
        return 0

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(render(entries), encoding="utf-8")
    print(f"Generated {output} ({len(entries)} assets)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
